policy_names: ["complex_wp_1_4611744"]
policy_layers: [[512,256,256]]
obstacles_config_paths: ["./config/obstacles_complex.yaml"]

train_config_path: "./config/train_limo.yaml"
test_name: "COMPLEXWP_UE_THR"
machine_name: remote
seed: 989877
episode_queue_length: 18

cuda: 3
torch_deterministic: true
build_path: "./9xlimotest_linux/UASRL.x86_64"
agent_config_path: "./config/agent_test.yaml"
headless: true
worker_id: 4
base_time: 1765457030
actor_std: 0.95

accumulate_data: true

total_episodes: 1000
metrics_log_interval: 25

decision_frame_period: 5
send_debug_action: false

save_path: "./results/"

cbf: false
d_safe: 0.3
d_safe_mul: 3
alpha: 2.0
cbf_min_forward_velocity: 0.05

uf: false
uf_action_type: 'distribution' # or sample