
policy_names: ["multy_test_4050747", "multy_test_4050747", "multy_test_4050747"]
policy_layers: [[128,128,128], [128,128,128], [128,128,128]]

obstacles_config_paths: ["./config/obstacles_complex.yaml", "./config/obstacles_simple.yaml"]

train_config_path: "./config/train_limo.yaml"
test_name: "test_name"
machine_name: personal
seed: 1234
episode_queue_length: 18
# complex: [complex_1_4165576, complex_0_4090216, complex_1_4124018]
# simple: 

cuda: 0
torch_deterministic: true
build_path: "./unity_build/9xlimotest_wind/UASRL.exe"
agent_config_path: "./config/agent_test.yaml"
headless: false
worker_id: 0
base_time: 1765457030

accumulate_data: true

total_episodes: 11
metrics_log_interval: 50
metrics_smoothing: 0.9

decision_frame_period: 5
send_debug_action: false

save_path: "./results/"