# --- Configurazione Progetto ---
project_name: "Unc_UASRL"
p_name: "simple_0_4164735"
cuda: 0

# --- dati ---
data_path: "./remote_results/"  # Percorso dati
data_test_name: "UTS_4612312"

save_path: "./unc_models/"  # Percorso salvataggio modelli
actor_path: "./models/"  

# --- Hyperparameter Optimization (HPO - Fase 1) ---
hpo_trials: 8      # Numero di tentativi Optuna
hpo_epochs: 3      # Epoche ridotte per la ricerca veloce

# --- Training Ensemble (Fase 2) ---
final_epochs: 10   # Epoche massime per il training vero
patience: 10        # Early stopping patience
batch_size: 512     # Dimensione del batch
k_models_total: 5   # Numero totale di reti da allenare
n_elites: 2         # Numero di reti migliori da tenere (Elites)